### ISSUE TITLE
您好，百度云链接失效了

### ISSUE THREAD

**Issue by hushuaiouc** [ZhaomingKong/Denoising-Comparison#1]

**Comment by ZhaomingKong** [comment]
您好，我目前不在国内，过两天看看怎么解决这个问题。谢谢

**Comment by muinocriz** [comment]
老哥，能补下百度盘的链接吗？谷歌的实在下不下来。

**Comment by ZhaomingKong** [comment]
我过两天看看吧，最近有点忙，可能挂个vpn.

**Comment by ZhaomingKong** [comment]
你好，我刚刚看到这个问题，我在美国上不了百度云，你看看我是不是能用QQ发给你？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhaomingKong/Denoising-Comparison"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 晚上7:40
收件人:&nbsp;"ZhaomingKong/Denoising-Comparison"<Denoising-Comparison@noreply.github.com&gt;;
抄送:&nbsp;"卖刻耳桥担"<531623594@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ZhaomingKong/Denoising-Comparison] 您好，百度云链接失效了 (#1)





 
老哥，能补下百度盘的链接吗？谷歌的实在下不下来。

**Comment by ZhaomingKong** [comment]
> _No description provided._
